# Generated by Django 2.0.2 on 2018-03-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_auto_20180312_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_town',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
